apiVersion: apps/v1
kind: Deployment
metadata:
  name: savings-acc-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: savings-acc-svc
  template:
    metadata:
      labels:
        app: savings-acc-svc
    spec:
      containers:
      - name: savings-acc-svc
        image: bkadambi/savings-acc-svc
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: savings-acc-svc
  labels:
    app: savings-acc-svc
spec:
  type: NodePort
  ports:
    - port: 9080
      nodePort: 32600
  selector:
    app: savings-acc-svc
